// STATION types
export const UPDATE_STATION_DETAILS_STARTED = 'UPDATE_STATION_DETAILS_STARTED';
export const UPDATE_STATION_DETAILS_FAILED = 'UPDATE_STATION_DETAILS_FAILED';
export const UPDATE_STATION_DETAILS_SUCCEEDED = 'UPDATE_STATION_DETAILS_SUCCEEDED';
export const UPDATE_STATION_SERVICES_STARTED = 'UPDATE_STATION_SERVICES_STARTED';
export const UPDATE_STATION_SERVICES_FAILED = 'UPDATE_STATION_SERVICES_FAILED';
export const UPDATE_STATION_SERVICES_SUCCEEDED = 'UPDATE_STATION_SERVICES_SUCCEEDED';

// SEARCH types
export const SEARCH_STATION_STARTED = 'SEARCH_STATION_STARTED';
export const SEARCH_STATION_FAILED = 'SEARCH_STATION_FAILED';
export const SEARCH_STATION_SUCCEEDED = 'SEARCH_STATION_SUCCEEDED';